version: 2
updates:
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
    time: "23:30"

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
